.PHONY: zsh
zsh:
	ln -snf $$(pwd)/zsh/zprezto ~/.zprezto
	ln -snf $$(pwd)/zsh/zprezto/runcoms/zlogin ~/.zlogin
	ln -snf $$(pwd)/zsh/zprezto/runcoms/zlogout ~/.zlogout
	ln -snf $$(pwd)/zsh/zprezto/runcoms/zprofile ~/.zprofile
	ln -snf $$(pwd)/zsh/zprezto/runcoms/zshenv ~/.zshenv
	ln -snf $$(pwd)/zsh/zshrc ~/.zshrc
	ln -snf $$(pwd)/zsh/zpreztorc ~/.zpreztorc

.PHONY: bash
bash:
	ln -snf $$(pwd)/bash/bashrc ~/.bashrc