# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.dotfiles/shells/zsh/oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="andi"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="$HOME/.dotfiles/shells/zsh/custom"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=( \
    git-prompt \
    history \
    last-working-dir \
    fzf \
    zsh-completions \
    zsh-syntax-highlighting \
    history-substring-search \
)

# required for zsh-completions, TODO: improve performance
autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh


# User configuration
# zsh options
setopt rm_star_silent # disable verification message for rm with *

# zsh plugin options
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none

# disable autocompletion from /etc/hosts and known_hosts
zstyle ':completion:*:ssh:*' hosts off

# env vars
if [[ "$OSTYPE" == darwin* ]]; then
  shared="$HOME/shared"
  export COPYFILE_DISABLE=true # don't add hidden files to tar archives
elif [[ "$OSTYPE" == linux* ]]; then
  shared="$HOME/shared"
fi

export VOLTA_HOME="${HOME}/.volta"
PATH="${VOLTA_HOME}/bin:${PATH}" # volta needs to come before /usr/bin
PATH="${PATH}:${HOME}/.local/bin" # pip
PATH="${PATH}:${HOME}/.npm/packages/bin" # npm
PATH="${PATH}:${HOME}/go/bin" # Go
PATH="${PATH}:${shared}/andreas/roaming/IT/shellscripts"
export PATH=$PATH
export LESS="-F -g -i -M -R -S -w -X -z-4"

if [[ -S "$SSH_AUTH_SOCK" ]]; then
  ln -sf "$SSH_AUTH_SOCK" /tmp/ssh-agent-$USER
fi

# aliases and functions
fix-dir-perms() {
  find "$1" -type d -print0 | xargs -0 chmod 0755
  find "$1" -type f -print0 | xargs -0 chmod 0644
}

alias gdiff="git diff --no-index"
json-diff() {
  a=$(mktemp)
  b=$(mktemp)
  jq -S . "$1" > "$a"
  jq -S . "$2" > "$b"
  gdiff "$a" "$b"
}
dir-diff() {
  diff --color=always -r --exclude .git "$1" "$2" | less
}
rpm-diff() {
  a=$(mktemp)
  b=$(mktemp)
  rpm -qlpv "$1" | awk '{print $NF " " $1 " " $3 " " $4}' | sort > "$a"
  rpm -qlpv "$2" | awk '{print $NF " " $1 " " $3 " " $4}' | sort > "$b"
  gdiff "$a" "$b"
}

rpm-extract() {
  rpm2cpio "$1" | cpio -idmv
}

if [ $commands[kubectl] ]; then
  # lazy load kubectl auto-completions on first run
  kubectl() {
    unfunction "$0"
    source <(kubectl completion zsh)
    $0 "$@"
  }
fi
alias k="kubectl"

# umask
umask 022

# custom commands
[ -f "${HOME}/.zshrc.local" ] && source "${HOME}/.zshrc.local"
