all: gnome firefox thunderbird obsidian

# enable fractional scaling in gnome
gnome:
	dconf load / < gnome-hidpi

firefox:
	flatpak --user override --env MOZ_ENABLE_WAYLAND=1 org.mozilla.firefox

thunderbird:
	flatpak --user override --env MOZ_ENABLE_WAYLAND=1 org.mozilla.Thunderbird

obsidian:
	flatpak --user override --socket=wayland md.obsidian.Obsidian
