# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.dotfiles/apps/zsh/oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="andi"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="$HOME/.dotfiles/apps/zsh/custom"

# PATH must be set before loading plugins (required for mise plugin to find mise binary, otherwise plugin gets disabled)
PATH="$PATH:$HOME/.local/bin"
PATH="$PATH:$HOME/go/bin" # Go
PATH="$PATH:$HOME/.cargo/bin" # Rust
PATH="$PATH:$HOME/.dotfiles/scripts"
export PATH=$PATH

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

# git-prompt: variables for prompt
# history: aliases
# last-working-dir: always open last dir
# fzf: ctrl+r
# git: aliases
# mise: manage Go/npm versions
# kubectl: aliases
# kubectx: variables for prompt
# zsh-autosuggestions
# zsh-syntax-highlighting
# zsh-completions (NOT in plugins, but fpath)

fzf_plugin=""
command -v fzf > /dev/null && fzf_plugin="fzf"

plugins=( \
    git-prompt \
    history \
    last-working-dir \
    ${fzf_plugin} \
    git \
    mise \
    kubectl \
    kubectx \
    zsh-autosuggestions \
    zsh-syntax-highlighting \
)

fpath+=${ZSH_CUSTOM}/plugins/zsh-completions/src
autoload -U compinit && compinit
source "$ZSH/oh-my-zsh.sh"


# User Configuration
# zsh options
setopt rm_star_silent # disable verification message for rm with *

# zsh plugin options (remove underline)
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none

# env vars
export EDITOR=vim
export LESS="-F -g -i -M -R -S -w -X -z-4 -x4"
export GOPROXY=https://proxy.golang.org,direct

if [[ "$OSTYPE" == darwin* ]]; then
  export COPYFILE_DISABLE=true # don't add hidden files to tar archives
elif [[ "$OSTYPE" == linux* ]]; then
  : #test -d /home/linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
if [[ -d /mnt/c/Windows ]]; then
  # WSL
  export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent-relay.socket
fi

# aliases and functions
if [[ "$HOSTNAME" == "andreas-thinkpad" ]]; then
  alias code="/usr/bin/code --ozone-platform=wayland"
fi

## files
dusch() {
  du -sch "$@" | sort -rh | head
}

alias gdiff="git diff --no-index"
dir-diff() {
  diff --color=always -r --exclude .git "$1" "$2" | less
}

## tools
rpm-extract() {
  rpm2cpio "$1" | cpio -idmv
}

unzip-mkdirs() {
  # https://stackoverflow.com/a/8108058
  for f in "$@"; do unzip -d "${f%*.zip}" "$f"; done
}

## bash
clean-history() {
  local DROP_REGEX="oc login|docker login|base64|pass|token"

  echo Dropping the following from the history:
  grep -Ei "$DROP_REGEX" ~/.zsh_history
  grep -Eiv "$DROP_REGEX" ~/.zsh_history | sponge ~/.zsh_history
  chmod 0600 ~/.zsh_history
  fc -R
  echo Done.
}

set-title() {
  DISABLE_AUTO_TITLE=true
  print -Pn "\e]2;$*\a"
}

# umask
umask 022

# custom commands
[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"
