#!/bin/bash
if [ "$XDG_SESSION_DESKTOP" = "i3" ]; then
  if [ "$HOSTNAME" = "agerstmayr-thinkpad" ] && xrandr | grep "HDMI-2 connected" > /dev/null; then
    xrandr --output HDMI-2 --mode 3840x2160 --dpi 192 --left-of eDP-1 --primary \
           --output eDP-1 --dpi 92
  fi

  xinput set-prop "Synaptics TM3276-031" "libinput Natural Scrolling Enabled" 1
  xinput set-prop "Synaptics TM3276-031" "libinput Click Method Enabled" 0 1 # clickfinger method (right click with two fingers)
fi
