#!/bin/bash
if [ "$XDG_SESSION_DESKTOP" = "i3" ]; then
  if [ "$HOSTNAME" = "agerstmayr-thinkpad" ] &&
    xrandr | grep "DP-1-1 connected" > /dev/null &&
    xrandr | grep "DP-1-2 connected" > /dev/null; then
    xrandr --output DP-1-1 --mode 3840x2160 --rate 30 --dpi 192 --left-of DP-1-2 --primary # left
    xrandr --output DP-1-2 --mode 3840x2160 --rate 30 --dpi 192 --right-of DP-1-1 # middle
    xrandr --output eDP-1  --auto                               --right-of DP-1-2 # right
  fi

  xinput set-prop "Synaptics TM3276-031" "libinput Natural Scrolling Enabled" 1
  xinput set-prop "Synaptics TM3276-031" "libinput Click Method Enabled" 0 1 # clickfinger method (right click with two fingers)
fi
