WGET := wget -nc --content-disposition -q

fetch:
	$(WGET) https://unsplash.com/photos/-27Pzw5c_kU/download?force=true
	$(WGET) https://unsplash.com/photos/5S9SeI-HFZA/download?force=true
	$(WGET) https://unsplash.com/photos/62V7ntlKgL8/download?force=true
	$(WGET) https://unsplash.com/photos/fAlDju_xqZY/download?force=true
	$(WGET) https://unsplash.com/photos/G5JDRSKi3uY/download?force=true
	$(WGET) https://unsplash.com/photos/-GwHS2piM_U/download?force=true
	$(WGET) https://unsplash.com/photos/hqnlAZeUnhI/download?force=true
	$(WGET) https://unsplash.com/photos/hRdRxnHyjxU/download?force=true
	$(WGET) https://unsplash.com/photos/K09d-v-U-E0/download?force=true
	$(WGET) https://unsplash.com/photos/Uet3BLFu5yQ/download?force=true
	$(WGET) https://unsplash.com/photos/UWebmzDCWjI/download?force=true
	$(WGET) https://unsplash.com/photos/YN_JWPDYVoM/download?force=true
