#!/bin/bash -eu

project=${PWD##*/}
datetime=$(date +%Y%m%d%H%M%S)

if [[ "$project" == "tempo-operator" ]]; then
  if kubectl get ns | grep -q openshift-apiserver; then
    if kubectl -n openshift-tempo-operator get subscription tempo-product 2>/dev/null; then
      echo "⏳ Deploying on OpenShift via OLM..."
      IMG_PREFIX=quay.io/agerstmayr OPERATOR_VERSION=$datetime.0.0 BUNDLE_VARIANT=openshift make docker-build docker-push bundle bundle-build bundle-push olm-upgrade reset
    else
      echo "⏳ Deploying on OpenShift via manifests..."
      IMG_PREFIX=quay.io/agerstmayr OPERATOR_VERSION=$datetime.0.0 BUNDLE_VARIANT=openshift make docker-build docker-push deploy reset
    fi
  else
    echo "⏳ Deploying on Kubernetes..."
    IMG_PREFIX=quay.io/agerstmayr OPERATOR_VERSION=$datetime.0.0 make docker-build deploy reset
  fi
  echo "✅ Done"
elif [[ "$PWD" == */observatorium/api ]]; then
  echo "⏳ Building and pushing image..."
  img=quay.io/agerstmayr/observatorium-api:$datetime
  DOCKER_REPO=quay.io/agerstmayr/observatorium-api OCI_BIN=docker make container VERSION=$datetime
  docker tag quay.io/agerstmayr/observatorium-api:latest quay.io/agerstmayr/observatorium-api:$datetime
  docker push $img
  echo
  echo "⚠️ Cannot deploy automatically, switch the TempoStack to Unmanaged and use this image: $img"
fi
