#!/bin/bash -eu
path="${1:-.}"
uid="${2:-$(id -u)}"
gid="${3:-$(id -g)}"

find "$path" '(' -user "$uid" -perm -u=w ')' -o \
             '(' -group "$gid" -perm -g=w ')' -o \
             '(' -perm -o=w ')'
