#!/bin/bash
# usage: kubecert minio.default.svc.cluster.local
set -eu

openssl req -x509 -newkey rsa:4096 -sha256 -days 36500 -nodes -keyout ca.key -out ca.crt -subj '/CN=Demo CA' 2> /dev/null
cat <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca
data:
  ca.crt: |
EOF
cat ca.crt | sed 's/^/    /'

for dns in "$@"
do
    cn="${dns//,*/}"
    subjectAltName="DNS:${dns//,/,DNS:}"
    openssl req -x509 -newkey rsa:4096 -sha256 -days 36500 -nodes -keyout "$cn.key" -out "$cn.crt" -CA ca.crt -CAkey ca.key -subj "/CN=$cn" -addext "subjectAltName=$subjectAltName" 2> /dev/null
    cat <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: $cn-certs
data:
  tls.key: $(base64 -w 0 "$cn.key")
  tls.crt: $(base64 -w 0 "$cn.crt")
  ca.crt: $(base64 -w 0 "ca.crt")
EOF
done
