#!/bin/bash
set -eu

namespacearg=""
while getopts "n:" flag
do
  case "${flag}" in
    n) namespacearg="-n ${OPTARG}";;
  esac
done
shift "$((OPTIND-1))"

kubectl $namespacearg apply -f - > /dev/null << EOF
apiVersion: v1
kind: Pod
metadata:
  name: kubedebug
spec:
  containers:
  - name: kubedebug
    image: ghcr.io/andreasgerstmayr/homelab/kubedebug:latest
EOF
kubectl $namespacearg wait --for=condition=Ready pod/kubedebug > /dev/null

exec kubectl $namespacearg exec -it kubedebug -- "$@"
