#!/bin/bash
set -eu

namespace="default"

while getopts "n:" flag
do
  case "${flag}" in
    n) namespace=${OPTARG};;
  esac
done
shift "$((OPTIND-1))"

kubectl -n "${namespace}" apply -f - > /dev/null << EOF
apiVersion: v1
kind: Pod
metadata:
  name: kubedebug
spec:
  containers:
  - name: kubedebug
    image: ghcr.io/andreasgerstmayr/homelab/kubedebug:latest
EOF
kubectl -n "${namespace}" wait --for=condition=Ready pod/kubedebug > /dev/null

exec kubectl -n "${namespace}" exec -it kubedebug -- "$@"
