#!/bin/bash
set -eu

kubectl apply -f - > /dev/null << EOF
apiVersion: v1
kind: Pod
metadata:
  name: kubedebug
spec:
  containers:
  - name: kubedebug
    image: ghcr.io/andreasgerstmayr/homelab/kubedebug:latest
EOF
kubectl wait --for=condition=Ready pod/kubedebug > /dev/null

exec kubectl exec -it kubedebug -- "$@"
