#!/bin/bash
set -eu

ip=$(minikube ip "$@")
iface=$(ip r | grep $ip | awk '{print $NF}')

sudo resolvectl dns    $iface 10.96.0.10
sudo resolvectl domain $iface cluster.local

echo "✅ DNS requests for *.cluster.local are now resolved through the CoreDNS instance of the minikube cluster."
