#!/usr/bin/env python3
import sys
import re

def read_file(path):
    with open(path) as f:
        content = f.read()
        content = content.replace("“", '"').replace("”", '"')
        content = re.sub(r"\s+", ' ', content)
        content = re.sub(r"\s+", ' ', content)
        content = content.replace(". ", ".\n")
        print(content)

if __name__ == "__main__":
    read_file(sys.argv[1])
