#!/bin/bash -eu
a=$(mktemp)
b=$(mktemp)
if [[ "$1" == "--ignore1" ]]; then
  rpm -qlpv "$3" | awk '{print $NF " " $5 " " $1 " " $3 " " $4}' | grep -Ev "$2" | sort > "$a"
  rpm -qlpv "$4" | awk '{print $NF " " $5 " " $1 " " $3 " " $4}' | sort > "$b"
elif [[ "$1" == "--ignore2" ]]; then
  rpm -qlpv "$3" | awk '{print $NF " " $5 " " $1 " " $3 " " $4}' | sort > "$a"
  rpm -qlpv "$4" | awk '{print $NF " " $5 " " $1 " " $3 " " $4}' | grep -Ev "$2" | sort > "$b"
else
  rpm -qlpv "$1" | awk '{print $NF " " $5 " " $1 " " $3 " " $4}' | sort > "$a"
  rpm -qlpv "$2" | awk '{print $NF " " $5 " " $1 " " $3 " " $4}' | sort > "$b"
fi
git diff --no-index "$a" "$b"
