#!/bin/bash -eu
a=$(mktemp)
b=$(mktemp)
if [[ "$1" == "--raw" ]]; then
  shift
  tar -tvf "$1" > "$a"
  tar -tvf "$2" > "$b"
elif [[ "$1" == "--no-perms" ]]; then
  shift
  AWK='{F=substr($0,index($0,$6)); sub("[^/]+/","",F); print F " " $3}'
  tar -tvf "$1" | awk "$AWK" | sort > "$a"
  tar -tvf "$2" | awk "$AWK" | sort > "$b"
else
  AWK='{F=substr($0,index($0,$6)); sub("[^/]+/","",F); print F " " $3 " " $1 " " $2}'
  tar -tvf "$1" | awk "$AWK" | sort > "$a"
  tar -tvf "$2" | awk "$AWK" | sort > "$b"
fi
git diff --no-index "$a" "$b"
