gnome:
	dconf load / < gnome

dash-to-dock:
	dconf load / < dash-to-dock

# hide application icon of Firefox RPM package
firefox-hide-rpm:
	printf '[Desktop Entry]\nNoDisplay=true\n' > ~/.local/share/applications/firefox.desktop
