#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# aliases
unalias rm

if [[ "$OSTYPE" == darwin* ]]; then
  local shared="$HOME/shared"
  export COPYFILE_DISABLE=true # don't add hidden files to tar archives
  alias netstat-open-ports="netstat -an | egrep 'Proto|LISTEN'"
elif [[ "$OSTYPE" == linux* ]]; then
  local shared="$HOME/shared"
  alias netstat-open-ports="netstat -anp | egrep 'Proto|LISTEN'"
elif [[ "$OSTYPE" == "cygwin" ]]; then
fi

# directory bookmarks
hash -d sem10="$shared/Uni/Semester10"
hash -d sem11="$shared/Uni/Semester11"

# zsh options
setopt rm_star_silent # disable verification message for rm with *
setopt clobber        # disable warning when redirecting output to existing file
unsetopt correct      # disable autocorrection
