#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ "$OSTYPE" == darwin* ]]; then
  local shared="$HOME/shared"
  export COPYFILE_DISABLE=true # don't add hidden files to tar archives
  export PATH=$PATH:~/Library/Python/3.7/bin:$shared/misc/IT/shellscripts
elif [[ "$OSTYPE" == linux* ]]; then
  if grep -q Microsoft /proc/version; then
    local shared="/mnt/c/Users/Andreas/shared"
  else
    local shared="$HOME/shared"
  fi
   export PATH=$PATH:$shared/misc/IT/shellscripts
elif [[ "$OSTYPE" == "cygwin" ]]; then
fi

# directory bookmarks
hash -d misc="$shared/misc"
hash -d uni="$shared/2018S"
hash -d gsoc="$shared/2018S/GSOC"

# zsh options
setopt rm_star_silent # disable verification message for rm with *
setopt clobber        # disable warning when redirecting output to existing file
unsetopt correct      # disable autocorrection
setopt PROMPT_SP      # show partial lines
alias scp='noglob scp' # workaround for scp path autocomplete on ubuntu
