#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# aliases
unalias rm

if [[ "$OSTYPE" == darwin* ]]; then
  local dropbox="$HOME/Dropbox"
  export COPYFILE_DISABLE=true # don't add hidden files to tar archives
  alias netstat-open-ports="netstat -an | egrep 'Proto|LISTEN'"
elif [[ "$OSTYPE" == linux* ]]; then
  local dropbox="/media/sf_Dropbox"
  alias netstat-open-ports="netstat -anp | egrep 'Proto|LISTEN'"
elif [[ "$OSTYPE" == "cygwin" ]]; then
  local dropbox="/cygdrive/c/Users/Andreas/Dropbox"
fi

# directory bookmarks
hash -d sem8="$dropbox/Uni/TU Wien/Semester8"
hash -d bac="$dropbox/Uni/TU Wien/Semester8/bachelor-thesis"
hash -d ben="$dropbox/Uni/TU Wien/Semester8/bachelor-thesis/benchmarks"
hash -d sem9="$dropbox/Uni/TU Wien/Semester9"

# zsh options
setopt rm_star_silent # disable verification message for rm with *
unsetopt correct      # disable autocorrection
