"" indent new line like the previous one
set autoindent

"" enable syntax highlighting
syntax on

if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.maxlinenr = '☰ '
let g:airline_symbols.colnr = ' '
